SocialMediaManagement/Controllers/DashboardPageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SocialMediaManagement.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SocialMediaManagement.Controllers
{
    public class DashboardPageController : Controller
    {
     [Authorize]
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        } 
    }
}

SocialMediaManagement/Controllers/HomePageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SocialMediaManagement.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SocialMediaManagement.Controllers
{
    public class HomePageController : Controller
    {
     
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        } 
    }
}

SocialMediaManagement/Views/HomePage/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<section class="bg--blue-0 section">
    <div class="_centeritems flex-column-m row">
        <div class="_span-5 col mw600-m pr-8p-offset-l tc-m">
            <h1 class="f800 mt500" style="color:blue"> Your performance monitoring and reporting flow, powered up </h1>
            <p class="f300" style="color:chocolate">Marketing professionals use access to track campaign results across different channels. Build customizable visual reports and let data insights lead the way. </p>
            <a class="button dib mx-auto-m px650 w-100p w-auto-ns" style="background-color:crimson" asp-area="" asp-controller="DashboardPage" asp-action="Index"> Get Started Now </a>

        </div>
        <div class="_span-7 col mt600-m mw600-m">
            <amp-img alt="dashboard picture" height="1218" layout="intrinsic" src="~/HomePageTemplate/img/Dashboard.jpg" width="2000" class="i-amphtml-layout-intrinsic i-amphtml-layout-size-defined i-amphtml-element i-amphtml-built i-amphtml-layout" i-amphtml-layout="intrinsic" style="--loader-delay-offset:244ms !important;">
                <i-amphtml-sizer class="i-amphtml-sizer" slot="i-amphtml-svc">
                    <img alt="dashboard picture" aria-hidden="true" class="i-amphtml-intrinsic-sizer" role="presentation" src="~/HomePageTemplate/img/Dashboard.jpg">
                </i-amphtml-sizer>
            </amp-img>
        </div>
    </div>
</section>