SocialMediaManagement/Controllers/HomePageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SocialMediaManagement.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SocialMediaManagement.Controllers
{
    public class HomePageController : Controller
    {
     
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        } 
    }
}

SocialMediaManagement/Views/Shared/_Footer.cshtml
<footer class="tc py600 bg--background dn-p">
    <div class="mw900-l mx-auto px350 flex-l flex-wrap-l justify-between-l w-100p">
        <a aria-label="access group" class="c--neutral-600 flex items-center w-33p w-auto-l" href="/?amp" title="access group" rel="amphtml" />

        <img src="~/HomePageTemplate/img/accessgroup-2-e1562166330117.png" alt="Company logo" height="150" width="150">
        <div class="flex justify-between mw-66p-m mw-none-l mx-auto mr0-l mt500 mt0-l px350 px0-l tc">
            <a class="c--text hover-c--twitter db pa350" href="https://twitter.com/home" target="_blank" rel="noopener noreferrer">
                <svg fill="currentColor" class="db h500 h450-ns mw200 w-auto" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" title="" aria-labelledby="svg-inline--twitter1315029923"><title id="svg-inline--twitter1315029923"></title><path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"></path></svg><span class="screenreader">
                    Access on Twitter
                </span>
            </a>
            <a class="c--text hover-c--instagram db pa350" href="https://www.instagram.com/" target="_blank" rel="noopener noreferrer">
                <svg fill="currentColor" class="db h500 h450-ns mw200 w-auto" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" title="" aria-labelledby="svg-inline--instagram1978763014"><title id="svg-inline--instagram1978763014"></title><path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"></path></svg><span class="screenreader">
                    Access  on Instagram
                </span>
            </a>
            <a class="c--text hover-c--linkedin db pa350" href="https://www.linkedin.com/" target="_blank" rel="noopener noreferrer">
                <svg fill="currentColor" class="db h500 h450-ns mw200 w-auto" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448.1 512" title="" aria-labelledby="svg-inline--linkedin1617000572"><title id="svg-inline--linkedin1617000572"></title><path d="M100.3 448H7.4V148.9h92.9V448zM53.8 108.1C24.1 108.1 0 83.5 0 53.8S24.1 0 53.8 0s53.8 24.1 53.8 53.8-24.1 54.3-53.8 54.3zM448 448h-92.7V302.4c0-34.7-.7-79.2-48.3-79.2-48.3 0-55.7 37.7-55.7 76.7V448h-92.8V148.9h89.1v40.8h1.3c12.4-23.5 42.7-48.3 87.9-48.3 94 0 111.3 61.9 111.3 142.3V448h-.1z"></path></svg><span class="screenreader">
                    Access on LinkedIn
                </span>
            </a>
            <a class="c--text hover-c--facebook db pa350" href="https://www.facebook.com/" target="_blank" rel="noopener noreferrer">
                <svg fill="currentColor" class="db h500 h450-ns mw200 w-auto" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 264 512" title="" aria-labelledby="svg-inline--facebook1482993333"><title id="svg-inline--facebook1482993333"></title><path d="M215.8 85H264V3.6C255.7 2.5 227.1 0 193.8 0 124.3 0 76.7 42.4 76.7 120.3V192H0v91h76.7v229h94V283h73.6l11.7-91h-85.3v-62.7c0-26.3 7.3-44.3 45.1-44.3z"></path></svg><span class="screenreader">
                    Access on Facebook
                </span>
            </a>
            <a class="c--text hover-c--pinterest db pa350" href="https://www.pinterest.com/" target="_blank" rel="noopener noreferrer">
                <svg fill="currentColor" class="db h500 h450-ns mw200 w-auto" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512" title="" aria-labelledby="svg-inline--pinterest1960150135"><title id="svg-inline--pinterest1960150135"></title><path d="M496 256c0 137-111 248-248 248-25.6 0-50.2-3.9-73.4-11.1 10.1-16.5 25.2-43.5 30.8-65 3-11.6 15.4-59 15.4-59 8.1 15.4 31.7 28.5 56.8 28.5 74.8 0 128.7-68.8 128.7-154.3 0-81.9-66.9-143.2-152.9-143.2-107 0-163.9 71.8-163.9 150.1 0 36.4 19.4 81.7 50.3 96.1 4.7 2.2 7.2 1.2 8.3-3.3.8-3.4 5-20.3 6.9-28.1.6-2.5.3-4.7-1.7-7.1-10.1-12.5-18.3-35.3-18.3-56.6 0-54.7 41.4-107.6 112-107.6 60.9 0 103.6 41.5 103.6 100.9 0 67.1-33.9 113.6-78 113.6-24.3 0-42.6-20.1-36.7-44.8 7-29.5 20.5-61.3 20.5-82.6 0-19-10.2-34.9-31.4-34.9-24.9 0-44.9 25.7-44.9 60.2 0 22 7.4 36.8 7.4 36.8s-24.5 103.8-29 123.2c-5 21.4-3 51.6-.9 71.2C65.4 450.9 0 361.1 0 256 0 119 111 8 248 8s248 111 248 248z"></path></svg><span class="screenreader">
                    Access on Pinterest
                </span>
            </a>
            <a class="c--text hover-c--youtube db pa350" href="https://www.youtube.com/" target="_blank" rel="noopener noreferrer">
                <svg fill="currentColor" class="db h500 h450-ns mw200 w-auto" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" title="" aria-labelledby="svg-inline--youtube370498327"><title id="svg-inline--youtube370498327"></title><path d="M549.655 124.083c-6.281-23.65-24.787-42.276-48.284-48.597C458.781 64 288 64 288 64S117.22 64 74.629 75.486c-23.497 6.322-42.003 24.947-48.284 48.597-11.412 42.867-11.412 132.305-11.412 132.305s0 89.438 11.412 132.305c6.281 23.65 24.787 41.5 48.284 47.821C117.22 448 288 448 288 448s170.78 0 213.371-11.486c23.497-6.321 42.003-24.171 48.284-47.821 11.412-42.867 11.412-132.305 11.412-132.305s0-89.438-11.412-132.305zm-317.51 213.508V175.185l142.739 81.205-142.739 81.201z"></path></svg><span class="screenreader">
                    Access on Youtube
                </span>
            </a>
        </div>
        <p class="f200 c--neutral-500 mt500 mt0-l w-100p tr-l">
            <span class="db di-ns">
                © Copyright 2022 access, Inc. All Rights Reserved.
            </span>
    </div>
</footer>

SocialMediaManagement/Views/Shared/_Header.cshtml
<header>
    <div class="bg--neutral-0 bg--neutral-100-l relative z9 ">
        <div class="f300 flex flex-column flex-row-l items-center justify-between mw900 mx-auto pa350-l">
            <div class="flex justify-between items-center px350 px0-l py350 py0-l w-100p w-auto-l">
                <div>
                    <a aria-label="access group" href="https://localhost:44394" title="access group" />

                    <img src="~/HomePageTemplate/img/accessgroup-2-e1562166330117.png" alt="Company logo" height="150" width="150 " />
                </div>
            </div>
      
            <div class="mobile-contact dn db-l">
                <div class="bg--blue-1100 bg--neutral-100-l flex inline-flex-l flex-column flex-row-l h500-l items-center-l w-100p">
                    <div class="db flex-l">
                        <div class="flex items-center">
                            <span class="dn dib-l fw-bold mr400">Contact</span>
                            <a class="c--text-inverse c--text-l f500 f300-l inline-flex items-center mr400 pa400 pa0-l js-sproutphonenumber">
                              
                                <span class="fw-bold fw-normal-l">+216xxxxxxxx</span>
                            </a>
                        </div>                    
                    </div>

                    <div class="wg-nav__right">
                        <div class="wg-nav__right__button-wrap">
                            <a href="https://localhost:44394/Identity/Account/Login"
                               class="wg-btn wg-nav__right__button wg-nav__right__grey wg-btn--gradient-animation">
                                <span>Log in</span>
                            </a>
                            <a href="https://localhost:44394/Identity/Account/Register"
                               class="wg-btn wg-nav__right__button wg-nav__right__red-main wg-btn--gradient-animation">
                                <span>Register</span>
                            </a>
                            
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</header>

SocialMediaManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Access </title>
    <link rel="shortcut icon" type="x-icon" href="/HomePageTemplate/img/accessgroup-2-e1562166330117.png" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Google fonts-->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,600;1,600&amp;display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,500;0,600;0,700;1,300;1,500;1,600;1,700&amp;display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,400;1,400&amp;display=swap" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    @*<link rel="stylesheet" href="~/css/site.css" />*@
    <link href="~/HomePageTemplate/css/site.css" rel="stylesheet" />
    <link href="~/HomePageTemplate/css/ampshared.css" rel="stylesheet" />
    <link href="~/HomePageTemplate/css/buttom.css" rel="stylesheet" />
    <link href="~/HomePageTemplate/css/signup.css" rel="stylesheet" />

</head>
<body>

    @*@Header part*@
    @Html.Partial("_Header")

    @*Body part*@

    @RenderBody()


    @*Footer part*@

    @Html.Partial("_Footer")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
         
            

SocialMediaManagement/Views/Shared/_LayoutDashboard.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"] - Access</title>
    <link rel="shortcut icon" type="x-icon" href="/HomePageTemplate/img/accessgroup-2-e1562166330117.png" />
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/DashboardPageTemplate/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/DashboardPageTemplate/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/DashboardPageTemplate/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/DashboardPageTemplate/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/DashboardPageTemplate/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="~/DashboardPageTemplate/index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>A</b>LT</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Admin</b>LTE</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="~/DashboardPageTemplate/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
                                <span class="hidden-xs">Alexander Pierce</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="~/DashboardPageTemplate/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                                    <p>
                                        Alexander Pierce - Web Developer
                                        <small>Member since Nov. 2012</small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <li class="user-body">
                                    <div class="row">
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Followers</a>
                                        </div>
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Sales</a>
                                        </div>
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Friends</a>
                                        </div>
                                    </div>
                                    <!-- /.row -->
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="#" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <!-- Control Sidebar Toggle Button -->
                        <li>
                            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- =============================================== -->
        <!-- Left side column. contains the sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                  <h2 style="color:red">Admin</h2>
                </div>
              
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header"> Main Nav </li>
                    <li><a href="https://localhost:44394/usermanagement"><i class="fa fa-book"></i> <span> User</span></a></li>
                    <li><a href="https://adminlte.io/docs"><i class="fa fa-book"></i> <span>Group</span></a></li>
                    <li><a href="https://adminlte.io/docs"><i class="fa fa-book"></i> <span>Add Account</span></a></li>
                    <li class="header"> Report Nav </li>
                    <li><a href="https://adminlte.io/docs"><i class="fa fa-book"></i> <span>Report</span></a></li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @RenderBody()

        </div>
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.4.18
            </div>
            <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE</a>.</strong> All rights
            reserved.
        </footer>

        <!-- Control Sidebar -->
        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="~/DashboardPageTemplate/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/DashboardPageTemplate/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="~/DashboardPageTemplate/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/DashboardPageTemplate/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/DashboardPageTemplate/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/DashboardPageTemplate/dist/js/demo.js"></script>
    <script>
        $(document).ready(function () {
            $('.sidebar-menu').tree()
        })
    </script>
</body>
</html>

SocialMediaManagement/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Access</title>
    <link rel="shortcut icon" type="x-icon" href="/HomePageTemplate/img/accessgroup-2-e1562166330117.png" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/HomePageTemplate/css/site.css" rel="stylesheet" />
    <link href="~/HomePageTemplate/css/ampshared.css" rel="stylesheet" />
    <link href="~/HomePageTemplate/css/buttom.css" rel="stylesheet" />
    <link href="~/HomePageTemplate/css/signup.css" rel="stylesheet" />
</head>
<body>
    <header>
        <partial name="_Header" />
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">


            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="HomePage" asp-action="Index"></a>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>
   

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SocialMediaManagement/Views/Shared/_RegisterLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Access</title>
    <link rel="shortcut icon" type="x-icon" href="/HomePageTemplate/img/accessgroup-2-e1562166330117.png" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/HomePageTemplate/css/site.css" rel="stylesheet" />
    <link href="~/HomePageTemplate/css/ampshared.css" rel="stylesheet" />
    <link href="~/HomePageTemplate/css/buttom.css" rel="stylesheet" />
    <link href="~/HomePageTemplate/css/signup.css" rel="stylesheet" />
</head>
<body>
    <header>
        <partial name="_Header" />
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="HomePage" asp-action="Index"></a>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>